// Copyright (c) 2023-2026 thorsphere.
// All Rights Reserved. Use is governed with GNU Affero General Public License v3.0
// that can be found in the LICENSE file.
package lpcode_test

import (
	"testing"

	"github.com/thorsphere/lpcode" // lpcode
	"github.com/thorsphere/tserr"
	"github.com/thorsphere/tsfio" // tsfio
)

// TestCodeFile tests the functionality of the Codefile struct and its methods.
// It creates a temporary directory, copies the header and footer files to the temporary directory,
// creates a new Codefile, starts the code file, writes a code snippet to the code file,
// finishes the code file, evaluates the contents of the code file against
// a golden file and finally removes the temporary directory and files.
func TestCodeFile(t *testing.T) {
	// Retrieve a temporary directory
	dn := tmpDir(t)
	// Retrieve path to header file
	th := path(t, dn, testcfheader)
	// Retrieve path to footer file
	tf := path(t, dn, testcffooter)

	// Copy the header file to the temporary directory
	if err := tsfio.CopyFile(
		&tsfio.Copy{
			Src: path(t, testdatadir, testcfheader),
			Dst: th,
		}); err != nil {
		// The test fails if the header file cannot be copied to the temporary directory
		t.Fatal(err)
	}

	// Copy the footer file to the temporary directory
	if err := tsfio.CopyFile(
		&tsfio.Copy{
			Src: path(t, testdatadir, testcffooter),
			Dst: tf,
		}); err != nil {
		// The test fails if the header file cannot be copied to the temporary directory
		t.Fatal(err)
	}

	// Create a new Codefile with the temporary directory and filename
	cf, err := lpcode.NewCodefile(dn, tsfio.Filename(testcfname))
	// The test fails if a Codefile cannot be created with the temporary directory and filename
	if err != nil {
		t.Fatal(err)
	}

	// Start the code file
	if err := cf.StartFile(); err != nil {
		// The test fails if the code file cannot be started
		t.Fatal(err)
	}

	// Write the code snippet generated by testIfErr to the code file
	if err := cf.WriteCode(testIfErr()); err != nil {
		// The test fails if the code cannot be written to the code file
		t.Fatal(err)
	}

	// Finish the code file
	if err := cf.FinishFile(); err != nil {
		// The test fails if the code file cannot be finished
		t.Fatal(err)
	}

	// Evaluate the contents of the code file against the golden file.
	if err := tsfio.EvalGoldenFile(&tsfio.Testcase{Name: testcfname, Data: cf.String()}); err != nil {
		// The test fails if the contents of the code file do not match the contents of the golden file
		t.Fatal(err)
	}

	// Remove the temporary directory, header file, footer file, code file and the temporary directory.
	rm(t, th)
	rm(t, tf)
	rm(t, cf.Filepath())
	rm(t, dn)
}

// TestFilepathNil tests the Filepath method of Codefile with a nil pointer.
// The test fails if Filepath does not return an empty string in case the Codefile is nil.
func TestFilepathNil(t *testing.T) {
	// Declare c as type *Code and assign nil.
	var c *lpcode.Codefile = nil
	// The test fails if Filepath does not return an empty string.
	if n := c.Filepath(); n != "" {
		t.Error(tserr.Empty("Filepath"))
	}
}

// TestStringNil tests the String method of Codefile with a nil pointer.
// The test fails if String does not return an empty string in case the Codefile is nil.
func TestStringNil2(t *testing.T) {
	// Declare c as type *Code and assign nil.
	var c *lpcode.Codefile = nil
	// The test fails if String does not return an empty string.
	if n := c.String(); n != "" {
		t.Error(tserr.Empty("String"))
	}
}

// TestStartFileNil tests the StartFile method of Codefile with a nil pointer.
// The test fails if StartFile does not return an error in case the Codefile is nil.
func TestStartFileNil(t *testing.T) {
	// Declare c as type *Code and assign nil.
	var c *lpcode.Codefile = nil
	// The test fails if StartFile does not return an error.
	if err := c.StartFile(); err == nil {
		t.Error(tserr.NilFailed("StartFile"))
	}
}

// TestFinishFileNil tests the FinishFile method of Codefile with a nil pointer.
// The test fails if FinishFile does not return an error in case the Codefile is nil.
func TestFinishFileNil(t *testing.T) {
	// Declare c as type *Code and assign nil.
	var c *lpcode.Codefile = nil
	// The test fails if FinishFile does not return an error.
	if err := c.FinishFile(); err == nil {
		t.Error(tserr.NilFailed("FinishFile"))
	}
}

// TestWriteCodeNil tests the WriteCode method of Codefile with a nil pointer.
// The test fails if WriteCode does not return an error in case the Codefile is nil.
func TestWriteCodeNil(t *testing.T) {
	// Declare c as type *Code and assign nil.
	var c *lpcode.Codefile = nil
	// The test fails if WriteCode does not return an error.
	if err := c.WriteCode(lpcode.NewCode()); err == nil {
		t.Error(tserr.NilFailed("WriteCode"))
	}
}

// TestWriteCodeNil tests the WriteCode method of Codefile with a nil pointer.
// The test fails if WriteCode does not return an error in case the Codefile is nil.
func TestWriteCodeNil2(t *testing.T) {
	// Retrieve a temporary directory
	dn := tmpDir(t)
	// Create a new Codefile with the temporary directory and filename
	c, err := lpcode.NewCodefile(dn, tsfio.Filename(testcfname))
	if err != nil {
		// The test fails if a Codefile cannot be created with the temporary directory and filename
		t.Fatal(err)
	}
	// The test fails if WriteCode does not return an error.
	if err := c.WriteCode(nil); err == nil {
		t.Error(tserr.NilFailed("WriteCode"))
	}
	// Remove the temporary directory.
	rm(t, dn)
}

// TestFormatNil tests the Format method of Codefile with a nil pointer.
// The test fails if Format does not return an error in case the Codefile is nil.
func TestFormatNil2(t *testing.T) {
	// Declare c as type *Code and assign nil.
	var c *lpcode.Codefile = nil
	// The test fails if Format does not return an error.
	if err := c.Format(); err == nil {
		t.Error(tserr.NilFailed("Format"))
	}
}
